### ISSUE TITLE
Remove additional "Secure your account" screen after users verify their login on new device

### ISSUE THREAD

**Issue by itsinz** [torusresearch/OpenLoginSdk#129]
Context:
On chrome desktop incognito, as a new device, I get the screen for "Verify your login"
I login to my existing device, approve the access from existing device. 
Then I go back to new device, "Verify your login" has a new share being updated, then it flicker to "Secure your account" screen (attached), before loading to openlogin homepage.
This flicker and switch to "Secure your account" should not be there.
<img width="1440" alt="Screenshot 2022-05-26 at 2 01 51 PM" src="https://user-images.githubusercontent.com/53069682/170427404-e3b9eb7f-72e8-492c-8108-b0b0adb3df29.png">

**Comment by chaitanyapotti** [comment]
Fixed
