### ISSUE TITLE
To send no-reply email from web3auth instead of tor.us

### ISSUE THREAD

**Issue by itsinz** [torusresearch/OpenLoginSdk#131]
Current:
For passwordless email, email is being sent from tor.us
<img width="750" alt="Screenshot 2022-05-26 at 2 29 58 PM" src="https://user-images.githubusercontent.com/53069682/170430999-7c4ecd9b-4244-421a-85b7-011e6855ff96.png">

We need to change it to be sent from web3auth.io

**Comment by chaitanyapotti** [comment]
This is solved in v5
