### ISSUE TITLE
Openlogin is broken

### ISSUE THREAD

**Issue by itsinz** [torusresearch/OpenLoginSdk#132]
Context:
I go to app.openlogin 

1. Authorised apps list
<img width="727" alt="Screenshot 2022-05-26 at 3 24 52 PM" src="https://user-images.githubusercontent.com/53069682/170439357-7486352c-1df0-428a-a14e-190181ccbf5d.png">

2. Delete app.tor.us 
<img width="733" alt="Screenshot 2022-05-26 at 3 24 56 PM" src="https://user-images.githubusercontent.com/53069682/170439448-50d1c857-1638-4fa7-a6f5-e5e06fbc3671.png">

3. Error 1: Go to account, it says I have 0/0 security factor  (first image is before deleting app.tor.us, second image is after deleting app.tor.us from authorised apps)
<img width="871" alt="Screenshot 2022-05-26 at 3 25 13 PM" src="https://user-images.githubusercontent.com/53069682/170439644-2aedc6c4-12e2-4f94-bfbd-b8d8ffa9f593.png">

<img width="629" alt="Screenshot 2022-05-26 at 3 25 22 PM" src="https://user-images.githubusercontent.com/53069682/170439658-62a99cd0-87a1-447d-b59d-83b066ff53d4.png">

4. Error 2: I logout, relogin, it shows the shares I have, my current device is there but I'm unable to login. it doesnt have the share. Chrome V101.0.0.0 (macOS, Desktop) (Current)

>> We should include the same friction for authorised dapps deletion and share deletion.
>> can we figure out why deleting access to app.tor.us would result in the 0/0 security factor screen?

**Comment by chaitanyapotti** [comment]
Fixed
