### ISSUE TITLE
Compatibility with webpack 5 (missing node polyfills)

### ISSUE THREAD

**Issue by tennox** [torusresearch/OpenLoginSdk#89]
When using this with webpack 5 I get a lot of errors regarding missing node functionality (`process`, `Buffer`, `crypto`)

Are polyfills the only way?

**Comment by chaitanyapotti** [comment]
Yes. you can also use the umd build otherwise

**Comment by akangaziz** [comment]
i have a similar problem with `vite`, i have opened a new issue here https://github.com/vitejs/vite/issues/7384
i think it's more on the `webpack` or `vite` rather than openlogin itself.

**Comment by xpluscal** [comment]
@chaitanyapotti how can web3auth be used with the umd version?
